# Generated by Django 4.2.4 on 2023-08-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectorapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_de_barra', models.CharField(max_length=100, unique=True)),
                ('contador', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
