# Generated by Django 4.2.4 on 2023-08-12 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectorapp', '0003_consultaproducto_total_consultas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultaproducto',
            name='total_consultas',
        ),
    ]
